stages:
  - build

flutter_build_android:
  stage: build
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - echo -n $KEYSTORE_FILE | base64 -d > $DECODE_KEY_PATH
    - flutter build apk --debug
  artifacts:
    paths:
      - build/app/outputs/apk
  tags:
    - flutter
