image: cirrusci/flutter:stable

stages:
  - check_format
  - analyze
  - test

flutter_check_format:
  stage: check_format
  script:
    - flutter format --set-exit-if-changed .

flutter_analyze:
  stage: analyze
  script:
    - flutter analyze

flutter_test:
  stage: test
  script:
    - flutter test
